# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Label'),
        ),
        migrations.AlterField(
            model_name='album',
            name='playcount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(default=2017),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='playcount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='music.Subgenre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='music.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(blank=True, to='music.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='playcount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='music.Subgenre'),
        ),
    ]
