# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('display_email', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('display_website', models.BooleanField(default=False)),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=250)),
                ('time_start', models.CharField(blank=True, choices=[(0, '000'), (1, '100'), (2, '200'), (3, '300'), (4, '400'), (5, '500'), (6, '600'), (7, '700'), (8, '800'), (9, '900'), (10, '1000'), (11, '1100'), (12, '1200'), (13, '1300'), (14, '1400'), (15, '1500'), (16, '1600'), (17, '1700'), (18, '1800'), (19, '1900'), (20, '2000'), (21, '2100'), (22, '2200'), (23, '2300')], max_length=4)),
                ('time_end', models.CharField(blank=True, choices=[(0, '000'), (1, '100'), (2, '200'), (3, '300'), (4, '400'), (5, '500'), (6, '600'), (7, '700'), (8, '800'), (9, '900'), (10, '1000'), (11, '1100'), (12, '1200'), (13, '1300'), (14, '1400'), (15, '1500'), (16, '1600'), (17, '1700'), (18, '1800'), (19, '1900'), (20, '2000'), (21, '2100'), (22, '2200'), (23, '2300')], max_length=4)),
                ('date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('dj', models.ManyToManyField(to='playlist.DJ')),
                ('genre', models.ManyToManyField(to='music.Genre')),
                ('subgenre', models.ManyToManyField(to='music.Subgenre')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='playlist.DJ')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('dj', models.ManyToManyField(to='playlist.DJ')),
                ('genre', models.ManyToManyField(to='music.Genre')),
                ('subgenre', models.ManyToManyField(to='music.Subgenre')),
            ],
        ),
        migrations.CreateModel(
            name='Spin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('index', models.IntegerField()),
                ('medium', models.CharField(blank=True, choices=[('D', 'Digital'), ('V', 'Vinyl'), ('C', 'CD'), ('T', 'Cassette'), ('L', 'Live'), ('O', 'Other')], max_length=1)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlist.Playlist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
            ],
        ),
    ]
