# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='music.Subgenre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='desc',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.ManyToManyField(blank=True, to='music.Genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='subgenre',
            field=models.ManyToManyField(blank=True, to='music.Subgenre'),
        ),
    ]
